In [1]:
import numpy as np

In [12]:
x=[[1,2,3],[3,6,7],[10,11,12]]
x

[[1, 2, 3], [3, 6, 7], [10, 11, 12]]

In [13]:
y = np.array(x)


In [14]:
y

array([[ 1,  2,  3],
       [ 3,  6,  7],
       [10, 11, 12]])

In [17]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [20]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.random.rand(5)

array([0.84291292, 0.30081043, 0.19866731, 0.09096987, 0.22843788])

In [26]:
np.random.rand(3,3)

array([[0.08017086, 0.51133768, 0.15407742],
       [0.82603002, 0.90239504, 0.79009672],
       [0.91417028, 0.01816787, 0.174135  ]])

In [41]:
rand=np.random.randint(1,100,20)
rand

array([48, 44, 31, 67, 20, 62, 90, 82, 98, 95, 95, 81,  5, 39,  5, 27, 43,
       77, 47, 81], dtype=int32)

In [44]:
 rand.reshape(4,5)

array([[48, 44, 31, 67, 20],
       [62, 90, 82, 98, 95],
       [95, 81,  5, 39,  5],
       [27, 43, 77, 47, 81]], dtype=int32)

In [45]:
np.max(rand)

np.int32(98)

In [46]:
np.min(rand)

np.int32(5)

In [47]:
np.argmax(rand)

np.int64(8)

In [48]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr[1:10:2]

array([1, 3, 5, 7, 9])

In [55]:
arr2=arr[2:11].copy()
arr2

array([99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr2[0:4]=99
arr2

array([99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr2d=np.array([[1,2,3],[5,6,7],[8,9,0]])
arr2d

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [73]:
arr2d[1:3,1:3]

array([[6, 7],
       [9, 0]])

In [74]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [76]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [81]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
arr/0

C:\Users\MTBD\AppData\Local\Temp\ipykernel_3968\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
C:\Users\MTBD\AppData\Local\Temp\ipykernel_3968\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [83]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])